### ISSUE TITLE
Margins

### ISSUE THREAD

**Issue by chppppp** [justinsteven/dostackbufferoverflowgood#4]
Love this tutorial and thank you so much for it. With that out of the way...

Why on gods green earth did you make the margins on the PDF so large? I use 2 page scrolling view for my big ol' monitors and your margins are literally insane. 

I tried to produce a PDF from the markdown but it doesnt pull the images. Could you provide a PDF with no margins or very small margins?

Thank you :)

**Comment by justinsteven** [comment]
Heya @chppppp 

Good call. The margins are a bit excessive. They are the default pandoc/xetex/latex margins.

However I'd rather not change the margins of the PDF or provide a separate smaller-margin copy of the PDF at this stage. People might be referencing pages by page number or in other way relying on a relatively stable PDF and so I'd rather my distribution of it be only one canonical version :)

Of course, the content is CC-BY 4.0 so you're welcome to take the content, remix it it any way and redistribute it providing you preserve me as the author.

I've added `BUILDING.md` to the repo to help you recompile the PDF. You might be interested in reading it and then doing the following:

```
pandoc -V geometry:margin=0.4in --latex-engine=xelatex dostackbufferoverflowgood_tutorial.md -o
 dostackbufferoverflowgood_tutorial.pdf
```

See https://pandoc.org/faqs.html#how-do-i-change-the-margins-in-pdf-output for more info.

Alternatively, github renders the markdown quite nicely. You might like to use it, or in some other way render the markdown and punch it out as a PDF.

Cheers!
Justin

**Comment by OJ** [comment]
![giphy](https://user-images.githubusercontent.com/28896/43370830-9aa5bcac-93c9-11e8-9a8b-44ec616954b2.gif)

**Comment by chppppp** [comment]
Thank you!
